#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Import-safe backend/core facade for Tuned Image Sorter v67.2.

This module is the stable boundary for a future Windows UI.
It intentionally does not parse CLI arguments, run the console wizard, or call
``main()`` on import. UI code should build a ``RunConfig`` and call
``run_pipeline(config, callbacks)`` or ``run(config, callbacks)``.

v69.6 / Этап 055 keeps the stable UI-facing API and adds friend-ready
portable package docs/verification on top of the confirmed launcher split. Heavy recognition/clustering
implementation details still live in ``face_sorter_mvp.py``.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any, Dict, Optional

try:  # package mode: import face_sorter_mvp.backend
    from . import face_sorter_mvp as _core
    from .core.config import (
        FaceRecord,
        ImageRecord,
        NullProgressCallbacks,
        ProgressCallbacks,
        ReviewDecision,
        RunConfig,
        RunResult,
        stages_for_mode,
    )
    from .core.constants import (
        DEFAULT_MODEL,
        DEFAULT_PROFILE,
        IMAGE_EXTENSIONS,
        KNOWN_MODELS,
        MODE_STAGE_MAP,
        PIPELINE_STAGES,
        PROJECT_FILENAME,
        SCRIPT_VERSION,
    )
    from .core.pipeline import (
        model_default_params,
        model_param_schema,
        run_config_from_namespace,
        run_config_from_profile,
        run_pipeline,
        validate_run_config,
        write_run_config_json,
    )
    from .core.project_state import (
        build_run_state_base,
        default_project_db_path,
        describe_run_state_for_user,
        ensure_project_structure,
        find_unfinished_result_dirs,
        legacy_run_state_path,
        load_project_config,
        project_dirs_payload,
        project_json_path,
        read_legacy_run_state,
        read_project_json,
        read_run_state,
        resume_mode_from_state,
        write_run_state,
    )
    from .core.stages import (
        run_apply_names_stage,
        run_assign_stage,
        run_cluster_stage,
        run_copy_stage,
        run_report_stage,
        run_review_clusters_stage,
        run_scan_stage,
    )
    from .core.api import (
        ApiValidationResult,
        CallbackEvent,
        ProjectSummary,
        QualityProfileInfo,
        RecordingProgressCallbacks,
        UiBackendApi,
        UI_SESSION_SCHEMA_VERSION,
        UiRecentProject,
        UiSessionState,
        config_to_ui_session_state,
        create_run_config,
        default_ui_session_state,
        default_ui_state_path,
        find_resume_projects,
        get_quality_profile_dicts,
        get_quality_profiles,
        inspect_project,
        load_ui_session_state,
        mode_stages,
        normalize_path,
        pipeline_modes,
        pipeline_stages,
        prepare_project_folder,
        prune_recent_projects,
        remember_recent_project,
        save_ui_session_state,
        suggest_output_dir,
        ui_backend_api,
        ui_session_state_from_dict,
        ui_session_to_run_config,
        update_ui_session_state,
        validate_config_for_ui,
    )
    from .core.self_test import (
        BackendSelfTestCheck,
        BackendSelfTestResult,
        run_backend_self_test,
        ui_contract_snapshot,
    )
    from .core.job import (
        BackendJob,
        BackendJobSnapshot,
        BackendRunner,
        create_backend_job,
        run_backend_job_sync,
    )
    from .core.ui_schema import (
        UI_SCHEMA_VERSION,
        UiFieldOption,
        UiFormSection,
        UiParameterSpec,
        UiRunConfigSchema,
        get_ui_form_sections,
        get_ui_parameter_schema,
        get_ui_run_config_schema,
        get_ui_run_config_schema_dict,
        profile_settings_diff,
        run_config_to_ui_values,
        ui_values_to_overrides,
        validate_ui_values_against_schema,
    )
    from .core.preflight import (
        PREFLIGHT_SCHEMA_VERSION,
        CORE_DISTRIBUTIONS,
        OPTIONAL_DISTRIBUTIONS,
        GPU_DISTRIBUTIONS,
        PackageStatus,
        GpuPreflightStatus,
        RuntimePreflightResult,
        package_status,
        collect_package_statuses,
        gpu_preflight,
        runtime_preflight,
        runtime_preflight_summary,
    )
    from .core.result_health import (
        RESULT_HEALTH_SCHEMA_VERSION,
        RESULT_HEALTH_STAGE,
        ResultHealthItem,
        ResultHealthSummary,
        build_result_health_summary,
        format_result_health_text,
    )
    from .core.status import (
        UI_STATUS_SCHEMA_VERSION,
        UI_SEVERITIES,
        UI_STATUS_SOURCES,
        UiIssue,
        UiStatusReport,
        UiStatusSummary,
        ui_issue,
        ui_status_report,
        summarize_status_report,
        merge_status_reports,
        human_error_guidance,
        humanize_issue,
        humanize_status_report,
        build_error_guidance_text,
        issue_from_exception,
        status_from_validation_result,
        status_from_preflight_result,
        status_from_self_test_result,
        status_from_job_snapshot,
    )
    from .core.review_ui import (
        REVIEW_UI_SCHEMA_VERSION,
        REVIEW_UI_ACTIONS,
        ReviewUiReportFile,
        ReviewUiProblemRow,
        ReviewUiProblemSummary,
        ReviewUiClusterRow,
        ReviewUiSnapshot,
        ReviewUiSaveResult,
        load_problem_files_summary,
        load_review_ui_snapshot,
        save_review_ui_decisions,
    )
    from .core.contract import (
        UI_CONTRACT_SCHEMA_VERSION,
        UI_CONTRACT_NAME,
        UI_CONTRACT_API_VERSION,
        UiContractSnapshot,
        UiContractCheckResult,
        ui_contract_freeze_snapshot,
        verify_ui_contract,
    )
    from .core.windows_packaging import (
        WINDOWS_PACKAGING_SCHEMA_VERSION,
        WINDOWS_PACKAGING_DIR,
        WINDOWS_PACKAGING_OUTPUT_DIR,
        WINDOWS_PACKAGING_FILES,
        FRIEND_READY_TOP_LEVEL_FILES,
        FRIEND_READY_DOC_TOKEN_CHECKS,
        WindowsPackagingFile,
        WindowsPackagingPlan,
        WindowsPackagingCheckResult,
        FriendReadySourceCheckResult,
        default_project_root,
        windows_packaging_plan,
        verify_windows_packaging,
        verify_friend_ready_source_layout,
    )
    from .core.ui_polish import (
        UI_POLISH_SCHEMA_VERSION,
        UI_POLISH_STAGE,
        UI_ICON_RELATIVE_PATH,
        UI_ICON_PNG_RELATIVE_PATH,
        UI_LANGUAGE_CHOICES,
        UI_THEME_CHOICES,
        UI_DENSITY_CHOICES,
        UiInstructionStep,
        UiInstructionSection,
        UiPolishSettings,
        UiPolishSnapshot,
        normalize_ui_language,
        effective_ui_language,
        normalize_ui_theme,
        normalize_ui_density,
        ui_text,
        ui_stage_text,
        get_ui_instruction_sections,
        ui_polish_settings_from_session,
        apply_ui_polish_settings_to_session,
        ui_polish_snapshot,
    )
    from .core.release import (
        RELEASE_CHECK_SCHEMA_VERSION,
        RELEASE_CHECK_STAGE,
        ReleaseCheckItem,
        ReleaseCheckResult,
        run_release_check,
    )
    from .core.ui_usability import (
        UI_USABILITY_SCHEMA_VERSION,
        UI_USABILITY_STAGE,
        UiUsabilityHint,
        UiUsabilitySnapshot,
        classify_path_state,
        build_run_summary,
        build_paths_summary,
        build_runtime_status_text,
        build_first_run_help_text,
        build_onboarding_checklist_text,
        build_beginner_action_map_text,
        build_quick_test_help_text,
        is_output_inside_input,
        get_ui_usability_hints,
        ui_usability_snapshot,
    )

    from .core.frozen_runtime import (
        FROZEN_RUNTIME_SCHEMA_VERSION,
        FROZEN_RUNTIME_STAGE,
        FrozenRuntimeInfo,
        is_frozen_app,
        app_base_dir,
        bundle_internal_dir,
        meipass_dir,
        source_project_root,
        frozen_runtime_info,
        frozen_runtime_summary,
    )
    from .ui import (
        UI_SKELETON_VERSION,
        is_pyside6_available,
        launch_ui,
    )
    from .reports import (
        apply_names,
        compute_cluster_review_rows,
        collect_ui_bug_report_diagnostics,
        create_bug_report,
        diagnostics_dir_for_output,
        ensure_review_decisions_for_rows,
        generate_html_report,
        generate_names_csv,
        generate_review_clusters_csv,
        generate_summary_csv,
        load_review_decisions,
        resolve_review_decision,
        review_clusters_console,
        summarize_diagnostics,
        write_names_csv_from_decisions,
        write_review_decisions_report,
    )
except ImportError:  # script-folder mode: import backend
    import face_sorter_mvp as _core  # type: ignore
    from core.config import (  # type: ignore
        FaceRecord,
        ImageRecord,
        NullProgressCallbacks,
        ProgressCallbacks,
        ReviewDecision,
        RunConfig,
        RunResult,
        stages_for_mode,
    )
    from core.constants import (  # type: ignore
        DEFAULT_MODEL,
        DEFAULT_PROFILE,
        IMAGE_EXTENSIONS,
        KNOWN_MODELS,
        MODE_STAGE_MAP,
        PIPELINE_STAGES,
        PROJECT_FILENAME,
        SCRIPT_VERSION,
    )
    from core.pipeline import (  # type: ignore
        model_default_params,
        model_param_schema,
        run_config_from_namespace,
        run_config_from_profile,
        run_pipeline,
        validate_run_config,
        write_run_config_json,
    )
    from core.project_state import (  # type: ignore
        build_run_state_base,
        default_project_db_path,
        describe_run_state_for_user,
        ensure_project_structure,
        find_unfinished_result_dirs,
        legacy_run_state_path,
        load_project_config,
        project_dirs_payload,
        project_json_path,
        read_legacy_run_state,
        read_project_json,
        read_run_state,
        resume_mode_from_state,
        write_run_state,
    )
    from core.stages import (  # type: ignore
        run_apply_names_stage,
        run_assign_stage,
        run_cluster_stage,
        run_copy_stage,
        run_report_stage,
        run_review_clusters_stage,
        run_scan_stage,
    )
    from core.api import (  # type: ignore
        ApiValidationResult,
        CallbackEvent,
        ProjectSummary,
        QualityProfileInfo,
        RecordingProgressCallbacks,
        UiBackendApi,
        UI_SESSION_SCHEMA_VERSION,
        UiRecentProject,
        UiSessionState,
        config_to_ui_session_state,
        create_run_config,
        default_ui_session_state,
        default_ui_state_path,
        find_resume_projects,
        get_quality_profile_dicts,
        get_quality_profiles,
        inspect_project,
        load_ui_session_state,
        mode_stages,
        normalize_path,
        pipeline_modes,
        pipeline_stages,
        prepare_project_folder,
        prune_recent_projects,
        remember_recent_project,
        save_ui_session_state,
        suggest_output_dir,
        ui_backend_api,
        ui_session_state_from_dict,
        ui_session_to_run_config,
        update_ui_session_state,
        validate_config_for_ui,
    )
    from core.self_test import (  # type: ignore
        BackendSelfTestCheck,
        BackendSelfTestResult,
        run_backend_self_test,
        ui_contract_snapshot,
    )
    from core.job import (  # type: ignore
        BackendJob,
        BackendJobSnapshot,
        BackendRunner,
        create_backend_job,
        run_backend_job_sync,
    )
    from core.ui_schema import (  # type: ignore
        UI_SCHEMA_VERSION,
        UiFieldOption,
        UiFormSection,
        UiParameterSpec,
        UiRunConfigSchema,
        get_ui_form_sections,
        get_ui_parameter_schema,
        get_ui_run_config_schema,
        get_ui_run_config_schema_dict,
        profile_settings_diff,
        run_config_to_ui_values,
        ui_values_to_overrides,
        validate_ui_values_against_schema,
    )
    from core.preflight import (  # type: ignore
        PREFLIGHT_SCHEMA_VERSION,
        CORE_DISTRIBUTIONS,
        OPTIONAL_DISTRIBUTIONS,
        GPU_DISTRIBUTIONS,
        PackageStatus,
        GpuPreflightStatus,
        RuntimePreflightResult,
        package_status,
        collect_package_statuses,
        gpu_preflight,
        runtime_preflight,
        runtime_preflight_summary,
    )
    from core.result_health import (  # type: ignore
        RESULT_HEALTH_SCHEMA_VERSION,
        RESULT_HEALTH_STAGE,
        ResultHealthItem,
        ResultHealthSummary,
        build_result_health_summary,
        format_result_health_text,
    )
    from core.status import (  # type: ignore
        UI_STATUS_SCHEMA_VERSION,
        UI_SEVERITIES,
        UI_STATUS_SOURCES,
        UiIssue,
        UiStatusReport,
        UiStatusSummary,
        ui_issue,
        ui_status_report,
        summarize_status_report,
        merge_status_reports,
        human_error_guidance,
        humanize_issue,
        humanize_status_report,
        build_error_guidance_text,
        issue_from_exception,
        status_from_validation_result,
        status_from_preflight_result,
        status_from_self_test_result,
        status_from_job_snapshot,
    )
    from core.review_ui import (  # type: ignore
        REVIEW_UI_SCHEMA_VERSION,
        REVIEW_UI_ACTIONS,
        ReviewUiReportFile,
        ReviewUiProblemRow,
        ReviewUiProblemSummary,
        ReviewUiClusterRow,
        ReviewUiSnapshot,
        ReviewUiSaveResult,
        load_problem_files_summary,
        load_review_ui_snapshot,
        save_review_ui_decisions,
    )
    from core.contract import (  # type: ignore
        UI_CONTRACT_SCHEMA_VERSION,
        UI_CONTRACT_NAME,
        UI_CONTRACT_API_VERSION,
        UiContractSnapshot,
        UiContractCheckResult,
        ui_contract_freeze_snapshot,
        verify_ui_contract,
    )
    from core.windows_packaging import (  # type: ignore
        WINDOWS_PACKAGING_SCHEMA_VERSION,
        WINDOWS_PACKAGING_DIR,
        WINDOWS_PACKAGING_OUTPUT_DIR,
        WINDOWS_PACKAGING_FILES,
        FRIEND_READY_TOP_LEVEL_FILES,
        FRIEND_READY_DOC_TOKEN_CHECKS,
        WindowsPackagingFile,
        WindowsPackagingPlan,
        WindowsPackagingCheckResult,
        FriendReadySourceCheckResult,
        default_project_root,
        windows_packaging_plan,
        verify_windows_packaging,
        verify_friend_ready_source_layout,
    )
    from core.ui_polish import (  # type: ignore
        UI_POLISH_SCHEMA_VERSION,
        UI_POLISH_STAGE,
        UI_ICON_RELATIVE_PATH,
        UI_ICON_PNG_RELATIVE_PATH,
        UI_LANGUAGE_CHOICES,
        UI_THEME_CHOICES,
        UI_DENSITY_CHOICES,
        UiInstructionStep,
        UiInstructionSection,
        UiPolishSettings,
        UiPolishSnapshot,
        normalize_ui_language,
        effective_ui_language,
        normalize_ui_theme,
        normalize_ui_density,
        ui_text,
        ui_stage_text,
        get_ui_instruction_sections,
        ui_polish_settings_from_session,
        apply_ui_polish_settings_to_session,
        ui_polish_snapshot,
    )
    from core.release import (  # type: ignore
        RELEASE_CHECK_SCHEMA_VERSION,
        RELEASE_CHECK_STAGE,
        ReleaseCheckItem,
        ReleaseCheckResult,
        run_release_check,
    )
    from core.ui_usability import (  # type: ignore
        UI_USABILITY_SCHEMA_VERSION,
        UI_USABILITY_STAGE,
        UiUsabilityHint,
        UiUsabilitySnapshot,
        classify_path_state,
        build_run_summary,
        build_paths_summary,
        build_runtime_status_text,
        build_first_run_help_text,
        build_onboarding_checklist_text,
        build_beginner_action_map_text,
        build_quick_test_help_text,
        is_output_inside_input,
        get_ui_usability_hints,
        ui_usability_snapshot,
    )

    from core.frozen_runtime import (  # type: ignore
        FROZEN_RUNTIME_SCHEMA_VERSION,
        FROZEN_RUNTIME_STAGE,
        FrozenRuntimeInfo,
        is_frozen_app,
        app_base_dir,
        bundle_internal_dir,
        meipass_dir,
        source_project_root,
        frozen_runtime_info,
        frozen_runtime_summary,
    )
    from ui import (  # type: ignore
        UI_SKELETON_VERSION,
        is_pyside6_available,
        launch_ui,
    )
    from reports import (  # type: ignore
        apply_names,
        compute_cluster_review_rows,
        collect_ui_bug_report_diagnostics,
        create_bug_report,
        diagnostics_dir_for_output,
        ensure_review_decisions_for_rows,
        generate_html_report,
        generate_names_csv,
        generate_review_clusters_csv,
        generate_summary_csv,
        load_review_decisions,
        resolve_review_decision,
        review_clusters_console,
        summarize_diagnostics,
        write_names_csv_from_decisions,
        write_review_decisions_report,
    )

ConsoleProgressCallbacks = _core.ConsoleProgressCallbacks
MODEL_REGISTRY = _core.MODEL_REGISTRY
QUALITY_PROFILES = _core.QUALITY_PROFILES

# Project/resume mutating helpers kept here for compatibility after Этап 024.
update_run_state_progress = _core.update_run_state_progress
mark_run_stage = _core.mark_run_stage


class SilentProgressCallbacks(NullProgressCallbacks):
    """No-op callbacks that also suppress legacy console completion prints.

    Useful as the default for embedded UI/backend calls. CLI keeps using
    ``ConsoleProgressCallbacks``.
    """

    handles_console_output = True


def run(config: RunConfig, callbacks: Optional[ProgressCallbacks] = None) -> RunResult:
    """Run the backend pipeline with UI-safe default callbacks.

    ``None`` means silent callbacks, which is better for GUI applications than
    console printing. CLI continues to use ``ConsoleProgressCallbacks`` in
    ``face_sorter_mvp.py``.
    """
    return run_pipeline(config, callbacks or SilentProgressCallbacks())


def build_config_from_project(project_dir: Path, *, mode: str = "all") -> RunConfig:
    """Load ``project.json`` and return a ``RunConfig`` suitable for run()."""
    data = load_project_config(Path(project_dir))
    data["mode"] = mode or data.get("mode", "all")
    return run_config_from_namespace(argparse.Namespace(**data))


def backend_capabilities() -> Dict[str, Any]:
    """Return stable metadata a UI can use to build forms and feature gates."""
    return {
        "version": SCRIPT_VERSION,
        "project_filename": PROJECT_FILENAME,
        "known_models": list(KNOWN_MODELS),
        "quality_profiles": list(QUALITY_PROFILES.keys()),
        "modes": list(MODE_STAGE_MAP.keys()),
        "pipeline_stages": list(PIPELINE_STAGES),
        "cli_only_modes": ["diagnose-gpu", "install-hint"],
        "supports_project_json": True,
        "supports_resume": True,
        "supports_review_clusters": True,
        "supports_progress_callbacks": True,
        "supports_package_main": True,
        "supports_diagnostics_report": True,
        "supports_cli_wizard_module": True,
        "supports_reports_modules": True,
        "supports_core_pipeline_owner": True,
        "supports_stage_modules": True,
        "supports_ui_api": True,
        "ui_api_version": 21,
        "supports_backend_self_test": True,
        "supports_backend_job_runner": True,
        "supports_ui_session_state": True,
        "supports_ui_parameter_schema": True,
        "supports_runtime_preflight": True,
        "supports_ui_status_report": True,
        "supports_ui_contract_freeze": True,
        "supports_pyside6_ui_skeleton": True,
        "supports_pyside6_ui_schema_session_form": True,
        "supports_pyside6_job_progress_polish": True,
        "supports_pyside6_resume_recent_ui": True,
        "supports_pyside6_reports_review_ui": True,
        "supports_windows_packaging": True,
        "supports_ui_polish": True,
        "supports_release_check": True,
        "supports_ui_usability_pass": True,
        "supports_ui_localization_help_pass": True,
        "supports_windows_onefolder_build_profiles": True,
        "supports_windows_no_console_gui_launcher": True,
        "supports_cli_diagnostics_launcher": True,
        "supports_friend_ready_portable_package": True,
        "supports_result_health_check": True,
        "supports_soft_cancel_request": True,
        "supports_hard_cancel": False,
        "refactor_stage": "Этап 055",
        "core_modules": [
            "core.constants",
            "core.config",
            "core.contracts",
            "core.project_state",
            "core.pipeline",
            "core.stages",
            "core.stage_scan",
            "core.stage_cluster",
            "core.stage_assign",
            "core.stage_copy",
            "core.stage_report",
            "core.stage_review",
            "core.api",
            "core.self_test",
            "core.job",
            "core.session",
            "core.ui_schema",
            "core.preflight",
            "core.status",
            "core.review_ui",
            "core.contract",
            "core.windows_packaging",
            "core.ui_polish",
            "core.release",
            "core.ui_usability",
            "core.frozen_runtime",
            "core.result_health",
            "reports",
            "ui",
            "ui.main_window",
            "i18n",
            "cli_wizard",
        ],
        "pipeline_owner": "core.pipeline",
        "stage_dispatch_owner": "core.stages",
        "legacy_algorithm_module": "face_sorter_mvp.py",
        "ui_contract": ui_contract_freeze_snapshot().to_dict(),
        "ui_api": ui_backend_api().to_dict(),
        "windows_packaging": windows_packaging_plan().to_dict(),
        "friend_ready_source_layout": verify_friend_ready_source_layout().to_dict(),
        "ui_polish": ui_polish_snapshot().to_dict(),
        "release_check": {"schema_version": RELEASE_CHECK_SCHEMA_VERSION, "stage": RELEASE_CHECK_STAGE},
        "ui_usability": ui_usability_snapshot().to_dict(),
        "frozen_runtime": frozen_runtime_info().to_dict(),
    }


__all__ = [
    "ImageRecord", "FaceRecord", "RunConfig", "RunResult", "ReviewDecision",
    "ProgressCallbacks", "NullProgressCallbacks", "SilentProgressCallbacks", "ConsoleProgressCallbacks",
    "PROJECT_FILENAME", "KNOWN_MODELS", "DEFAULT_MODEL", "MODEL_REGISTRY",
    "QUALITY_PROFILES", "DEFAULT_PROFILE", "IMAGE_EXTENSIONS",
    "PIPELINE_STAGES", "MODE_STAGE_MAP",
    "stages_for_mode", "run_pipeline", "run", "validate_run_config",
    "run_config_from_namespace", "run_config_from_profile", "write_run_config_json",
    "model_param_schema", "model_default_params", "project_json_path",
    "legacy_run_state_path", "ensure_project_structure", "project_dirs_payload",
    "default_project_db_path", "read_project_json", "read_legacy_run_state",
    "read_run_state", "load_project_config", "build_config_from_project",
    "build_run_state_base", "write_run_state", "update_run_state_progress",
    "mark_run_stage", "find_unfinished_result_dirs", "resume_mode_from_state",
    "describe_run_state_for_user", "create_bug_report", "collect_ui_bug_report_diagnostics", "summarize_diagnostics", "diagnostics_dir_for_output", "generate_summary_csv",
    "generate_html_report", "generate_names_csv", "generate_review_clusters_csv",
    "compute_cluster_review_rows", "load_review_decisions", "resolve_review_decision",
    "write_review_decisions_report", "ensure_review_decisions_for_rows",
    "write_names_csv_from_decisions", "apply_names", "review_clusters_console",
    "run_scan_stage", "run_cluster_stage", "run_assign_stage", "run_copy_stage",
    "run_report_stage", "run_review_clusters_stage", "run_apply_names_stage",
    "ApiValidationResult", "QualityProfileInfo", "ProjectSummary",
    "CallbackEvent", "RecordingProgressCallbacks", "UiBackendApi",
    "ui_backend_api", "normalize_path", "suggest_output_dir",
    "get_quality_profiles", "get_quality_profile_dicts", "create_run_config",
    "validate_config_for_ui", "inspect_project", "find_resume_projects",
    "prepare_project_folder", "pipeline_modes", "pipeline_stages", "mode_stages",
    "UI_SESSION_SCHEMA_VERSION", "UiRecentProject", "UiSessionState",
    "default_ui_state_path", "default_ui_session_state",
    "ui_session_state_from_dict", "load_ui_session_state",
    "save_ui_session_state", "update_ui_session_state",
    "remember_recent_project", "prune_recent_projects",
    "config_to_ui_session_state", "ui_session_to_run_config",
    "UI_SCHEMA_VERSION", "UiFieldOption", "UiParameterSpec",
    "UiFormSection", "UiRunConfigSchema", "get_ui_form_sections",
    "get_ui_parameter_schema", "get_ui_run_config_schema",
    "get_ui_run_config_schema_dict", "profile_settings_diff",
    "run_config_to_ui_values", "ui_values_to_overrides",
    "validate_ui_values_against_schema",
    "PREFLIGHT_SCHEMA_VERSION", "CORE_DISTRIBUTIONS",
    "OPTIONAL_DISTRIBUTIONS", "GPU_DISTRIBUTIONS",
    "PackageStatus", "GpuPreflightStatus", "RuntimePreflightResult",
    "package_status", "collect_package_statuses", "gpu_preflight",
    "runtime_preflight", "runtime_preflight_summary",
    "RESULT_HEALTH_SCHEMA_VERSION", "RESULT_HEALTH_STAGE",
    "ResultHealthItem", "ResultHealthSummary",
    "build_result_health_summary", "format_result_health_text",
    "UI_STATUS_SCHEMA_VERSION", "UI_SEVERITIES", "UI_STATUS_SOURCES",
    "UiIssue", "UiStatusReport", "UiStatusSummary",
    "ui_issue", "ui_status_report", "summarize_status_report",
    "merge_status_reports", "issue_from_exception",
    "status_from_validation_result", "status_from_preflight_result",
    "status_from_self_test_result", "status_from_job_snapshot",
    "REVIEW_UI_SCHEMA_VERSION", "REVIEW_UI_ACTIONS",
    "ReviewUiReportFile", "ReviewUiProblemRow", "ReviewUiProblemSummary",
    "ReviewUiClusterRow", "ReviewUiSnapshot", "ReviewUiSaveResult",
    "load_problem_files_summary", "load_review_ui_snapshot", "save_review_ui_decisions",
    "UI_CONTRACT_SCHEMA_VERSION", "UI_CONTRACT_NAME", "UI_CONTRACT_API_VERSION",
    "UiContractSnapshot", "UiContractCheckResult",
    "ui_contract_freeze_snapshot", "verify_ui_contract",
    "WINDOWS_PACKAGING_SCHEMA_VERSION", "WINDOWS_PACKAGING_DIR",
    "WINDOWS_PACKAGING_OUTPUT_DIR", "WINDOWS_PACKAGING_FILES",
    "FRIEND_READY_TOP_LEVEL_FILES", "FRIEND_READY_DOC_TOKEN_CHECKS",
    "WindowsPackagingFile", "WindowsPackagingPlan", "WindowsPackagingCheckResult",
    "FriendReadySourceCheckResult",
    "default_project_root", "windows_packaging_plan", "verify_windows_packaging",
    "verify_friend_ready_source_layout",
    "UI_POLISH_SCHEMA_VERSION", "UI_POLISH_STAGE", "UI_ICON_RELATIVE_PATH", "UI_ICON_PNG_RELATIVE_PATH",
    "UI_LANGUAGE_CHOICES", "UI_THEME_CHOICES", "UI_DENSITY_CHOICES",
    "UiInstructionStep", "UiInstructionSection", "UiPolishSettings", "UiPolishSnapshot",
    "normalize_ui_language", "effective_ui_language", "normalize_ui_theme", "normalize_ui_density",
    "ui_text", "ui_stage_text", "get_ui_instruction_sections", "ui_polish_settings_from_session",
    "apply_ui_polish_settings_to_session", "ui_polish_snapshot",
    "RELEASE_CHECK_SCHEMA_VERSION", "RELEASE_CHECK_STAGE", "ReleaseCheckItem",
    "ReleaseCheckResult", "run_release_check",
    "UI_USABILITY_SCHEMA_VERSION", "UI_USABILITY_STAGE", "UiUsabilityHint", "UiUsabilitySnapshot",
    "classify_path_state", "build_run_summary", "build_paths_summary",
    "build_runtime_status_text", "build_first_run_help_text",
    "build_onboarding_checklist_text", "build_quick_test_help_text", "is_output_inside_input",
    "get_ui_usability_hints", "ui_usability_snapshot",
    "FROZEN_RUNTIME_SCHEMA_VERSION", "FROZEN_RUNTIME_STAGE", "FrozenRuntimeInfo",
    "is_frozen_app", "app_base_dir", "bundle_internal_dir", "meipass_dir",
    "source_project_root", "frozen_runtime_info", "frozen_runtime_summary",
    "UI_SKELETON_VERSION", "is_pyside6_available", "launch_ui",
    "BackendSelfTestCheck", "BackendSelfTestResult",
    "run_backend_self_test", "ui_contract_snapshot",
    "BackendJob", "BackendJobSnapshot", "BackendRunner",
    "create_backend_job", "run_backend_job_sync",
    "backend_capabilities",
]
